site_name: Harsh Cloud
site_url: https://harshcloud.com/
site_dir: "build/"
edit_uri: ""
copyright: "© Harsh Cloud"
site_author: "Harsh Jain"
site_description: "Harsh Cloud"

theme:
  name: material
  custom_dir: material
  language: "en"
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  features:
  - content.tabs.link
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Repo Details
repo_url: "https://github.com/hrkj-18/harshcloud.com"
repo_name: hrkj-18/harshcloud.com

plugins:
  - search:
      lang: en

# Extra Configuration for Material Theme

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/hrkj-18"
      name: Harsh Jain on Github
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/hrkj-18"
      name: Harsh Jain on Twitter
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/hrkj-18"
      name: Harsh Jain on Linkedin
    - icon: fontawesome/brands/facebook
      link: "https://facebook.com/hrkj-18"
      name: Harsh Jain on Facebook
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/hrkj-18"
      name: Harsh Jain on Instagram
    # - icon: fontawesome/brands/terminal
    #   link: "https://harshjain.dev"
    #   name: Harsh Jain
  feature:
    tabs: true

#  analytics:
#   provider: google
#   property: UA-XXXXXXXX-X

# Page tree
nav:
  - Home: index.md
  - AWS:
    - Index: aws/index.md
  - AZ-900:
    - Cloud Computing: az-900/cloud-computing.md
    - Azure Core Services: az-900/azure-core-services.md
    - Security, Privacy, Compliance and Trust: az-900/security-privacy-complaince-trust.md
    - Cost Management and SLA: az-900/cost-management-and-sla.md